//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbKeyWord
    {
        public string word_id { get; set; }
        public string sen_id { get; set; }
    
        public virtual tbActionWord tbActionWord { get; set; }
        public virtual tbKWord tbKWord { get; set; }
    }
}
